Repository WildCodeSchool/orleans-0219-php-studentmanager, pull requests merged in 2019-07, with the labels that each got.

#67 Fix sprint04 sauvegarder
  src/Entity/Student.php
  templates/student/_form.html.twig
  templates/student/edit.html.twig
  templates/student/new.html.twig
Labels: reviewed by PO

#66 one clic on air
  assets/js/checkindate.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  composer.json
  composer.lock
  phpstan.neon
  src/Controller/CheckinDateController.php
  src/Entity/Presence.php
  src/Entity/User.php
  src/Repository/PresenceRepository.php
  src/Service/DateService.php
  symfony.lock
  templates/base.html.twig
  templates/checkin_date/index.html.twig
Labels: reviewed by PO

#68 Us04 create checkindatebutton
  assets/images/wild-code-school-la-loupe-116.jpg
  assets/scss/app.scss
  src/Controller/CheckinDateController.php
  src/Entity/User.php
  templates/checkin_date/index.html.twig
  templates/navbar.html.twig
Labels: changes made, reviewed by PO

#70 Fix us04 create checkindatebutton
  src/Controller/CheckinDateController.php
Labels: reviewed by PO

#72 Fix2 us04 create checkindatebutton
  assets/scss/app.scss
  templates/checkin_date/index.html.twig
Labels: reviewed by PO

#74 Sprint03 us13 checkboxrememberme
  assets/scss/app.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/framework.yaml
  config/packages/security.yaml
  src/Controller/CheckinDateController.php
  src/Controller/SecurityController.php
  src/Controller/SessionController.php
  src/Controller/StudentController.php
  src/Entity/User.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
  templates/navbar.html.twig
  templates/security/login.html.twig
Labels: reviewed by PO

#76 front-login
  assets/images/wild-code-school-la-loupe-49.jpg
  assets/scss/app.scss
  composer.json
  composer.lock
  templates/security/login.html.twig
Labels: reviewed by PO

#75 items qui apparaissent selon les roles et animation css
  assets/scss/app.scss
  phpstan.neon
  templates/navbar.html.twig
Labels: reviewed by PO

#79 style on air
  assets/scss/app.scss
  templates/checkin_date/index.html.twig
  templates/footer.html.twig
Labels: reviewed by PO

#82 fix page edit
  assets/images/testLum72.jpg
  assets/images/you-x-ventures-1437336-unsplash.jpg
  assets/scss/app.scss
  templates/base.html.twig
  templates/student/_form.html.twig
  templates/student/edit.html.twig
  templates/student/new.html.twig
Labels: reviewed by PO

#83 centrage du login
  assets/scss/app.scss
Labels: reviewed by PO

#84 Fix id student
  src/Controller/StudentController.php
Labels: reviewed by PO

#85 centrage du login et css register
  assets/images/wild-code-school-la-loupe-115.jpg
  assets/scss/app.scss
  templates/registration/registration.html.twig
Labels: reviewed by PO

#86 correction des redirections
  src/Controller/SecurityController.php
  templates/navbar.html.twig
  templates/security/login.html.twig
Labels: reviewed by PO

#87 correction de route
  templates/security/login.html.twig
Labels: reviewed by PO

#88 Dev
  assets/images/testLum72.jpg
  assets/images/wild-code-school-la-loupe-115.jpg
  assets/images/wild-code-school-la-loupe-49.jpg
  assets/images/you-x-ventures-1437336-unsplash.jpg
  assets/scss/app.scss
  composer.json
  composer.lock
  phpstan.neon
  src/Controller/SecurityController.php
  src/Controller/StudentController.php
  templates/base.html.twig
  templates/checkin_date/index.html.twig
  templates/footer.html.twig
  templates/navbar.html.twig
  templates/registration/registration.html.twig
  templates/security/login.html.twig
  templates/student/_form.html.twig
  templates/student/edit.html.twig
  templates/student/new.html.twig
Labels: reviewed by PO

#78 Sprint04 us21 forgot password
  .env
  config/services.yaml
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  src/Entity/User.php
  src/Form/StudentType.php
  templates/navbar.html.twig
  templates/security/forgotten_password.html.twig
  templates/security/login.html.twig
  templates/security/reset_password.html.twig
Labels: reviewed by PO

#89 Dev
  .env
  config/services.yaml
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  src/Entity/User.php
  src/Form/StudentType.php
  templates/navbar.html.twig
  templates/security/forgotten_password.html.twig
  templates/security/login.html.twig
  templates/security/reset_password.html.twig
Labels: reviewed by PO

#90 style flash message ok
  assets/scss/_vars.scss
  assets/scss/app.scss
  templates/base.html.twig
  templates/checkin_date/index.html.twig
Labels: reviewed by PO

#93 css
  assets/scss/app.scss
  src/Form/StudentType.php
  templates/student/_form.html.twig
Labels: reviewed by PO

#94 Fix style dashboard
  assets/scss/app.scss
  templates/student/edit.html.twig
  templates/student/index.html.twig
Labels: reviewed by PO

#96 fix redirection et corrections des erreurs
  assets/scss/app.scss
  assets/scss/app.scss.orig
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  src/Entity/User.php
  src/Form/RegistrationType.php
  src/Form/StudentType.php
  templates/checkin_date/index.html.twig
  templates/navbar.html.twig
  templates/registration/registration.html.twig
  templates/student/edit.html.twig
  templates/student/index.html.twig
  templates/student/show.html.twig
Labels: reviewed by PO

#97 fix style student edit
  assets/scss/app.scss
  templates/student/_form.html.twig
  templates/student/edit.html.twig
  templates/student/show.html.twig
Labels: reviewed by PO

#98 fix style student show
  assets/scss/_vars.scss
  assets/scss/app.scss
  templates/student/show.html.twig
Labels: corrections done, reviewed by PO

#99 fix tyle checkin + hour changes
  assets/scss/app.scss
  src/Service/DateService.php
  templates/checkin_date/index.html.twig
Labels: reviewed by PO

#100 change birthdaytype and length max to 15 for social number
  src/Entity/Student.php
  src/Form/StudentType.php
Labels: reviewed by PO

#101 Dev to master
  assets/scss/_vars.scss
  assets/scss/app.scss
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  src/Entity/Student.php
  src/Entity/User.php
  src/Form/RegistrationType.php
  src/Form/StudentType.php
  src/Service/DateService.php
  templates/base.html.twig
  templates/checkin_date/index.html.twig
  templates/layoutAdmin.html.twig
  templates/navbar.html.twig
  templates/registration/registration.html.twig
  templates/student/_form.html.twig
  templates/student/edit.html.twig
  templates/student/index.html.twig
  templates/student/show.html.twig
Labels: reviewed by PO

#102 Btn login animation
  assets/js/app.js
  assets/js/checkindate.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  config/packages/security.yaml
  src/Controller/RegistrationController.php
  src/Form/StudentType.php
  templates/base.html.twig
  templates/btn-login-animation.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/navbar.html.twig
  templates/registration/registration.html.twig
  templates/security/forgotten_password.html.twig
  templates/security/login.html.twig
  templates/security/reset_password.html.twig
  templates/student/_form.html.twig
  templates/student/edit.html.twig
  templates/student/new.html.twig
  templates/student/show.html.twig
Labels: changes requested

#103 change margin form to disable scroll
  assets/scss/app.scss
Labels: corrections done

#105 fix style footer
  assets/scss/app.scss
  templates/footer.html.twig
Labels: reviewed by PO

#106 fix style ok
  assets/js/app.js
  assets/scss/app.scss
  templates/base.html.twig
Labels: reviewed by PO

#107 debug date + style login
  assets/scss/app.scss
  templates/student/_delete_form.html.twig
  templates/student/index.html.twig
Labels: reviewed by PO

#109 Fix style
  assets/scss/_vars.scss
  assets/scss/app.scss
  src/Service/DateService.php
  templates/base.html.twig
  templates/footer.html.twig
  templates/registration/registration.html.twig
  templates/security/forgotten_password.html.twig
  templates/security/login.html.twig
  templates/student/index.html.twig
Labels: conflicts, reviewed by PO

#108 suppression du bouton tableau de bord coté utilisateur
  templates/student/index.html.twig
  templates/student/show.html.twig
Labels: conflicts

#110 soulignement item navbar
  assets/scss/app.scss
Labels: reviewed by PO

#112 fix css + résolution du problème d'id pour le profil et suppression d…
  assets/scss/app.scss
  src/Controller/StudentController.php
  src/Form/StudentType.php
  templates/navbar.html.twig
  templates/security/forgotten_password.html.twig
  templates/security/reset_password.html.twig
  templates/student/edit.html.twig
  templates/student/show.html.twig
Labels: reviewed by PO

#113 correction assert leght champs pole emploi
  src/Entity/Student.php
Labels: corrections done, reviewed by PO

#115 Fix style
  templates/security/login.html.twig
  templates/student/_delete_form.html.twig
  templates/student/index.html.twig
Labels: reviewed by PO
